/* matchedfilter on the Apple GPU: host side.
 *
 * Owns the Metal device, compiles metal/kernels.metal at run time (the
 * source is embedded at build time, so no Xcode `metal` tool is needed), and
 * drives the kernels.  See kernels.metal for what each one does and
 * mf_metal.h for the contract, which is ap_mf_run's.
 *
 * Every buffer is in unified memory.  Spectra are written straight into
 * GPU-visible storage at ingest, and peaks are read straight out of it after a
 * run, so there is no transfer step to schedule or overlap.
 */
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mf_metal.h"
#include "mf_metal_src.h"   /* generated by setup.py: static const char MFM_SRC[] */

/* Must match struct Params in kernels.metal field for field. */
typedef struct {
  uint32_t n, ntl, ndl, dinner, d0, t0, npairs, pair0, nchunk, nb, bs, ws, we;
  float t2;
  uint32_t A, B, W2, H;
} mfm_params;

#define TILE 4096          /* complex values per FFT threadgroup */

/* Values per thread and stage radix; environment overrides are for tuning.
   Measured on an M2 (tools/metal_tune.py): 8/8 is fastest from 2048 up and
   within 5% below, and 16/16 is 25% slower at 4096 -- more values per thread
   costs occupancy faster than fewer stages repays it. */
static int g_vpt = 8, g_radx = 8;
#define VPT  g_vpt
#define RADX g_radx
static double g_gpu_seconds;
double mfm_last_gpu_seconds(void) { return g_gpu_seconds; }

static char g_err[512];
static void set_err(NSString *s) {
  snprintf(g_err, sizeof g_err, "%s", s ? [s UTF8String] : "unknown error");
}
const char *mfm_last_error(void) { return g_err[0] ? g_err : NULL; }

static id<MTLDevice> g_dev;
static id<MTLCommandQueue> g_queue;
static NSMutableDictionary<NSString *, id<MTLLibrary>> *g_libs;
static NSString *g_src;

static int env_int(const char *name, int def) {
  const char *e = getenv(name);
  return (e && *e) ? atoi(e) : def;
}

static int ilog2(size_t x) { int l = 0; while ((size_t)1 << l < x) l++; return l; }
static int is_pow2(size_t x) { return x && !(x & (x - 1)); }

static int init_device(void) {
  static dispatch_once_t once;
  static int ok = 0;
  dispatch_once(&once, ^{
    @autoreleasepool {
      g_dev = MTLCreateSystemDefaultDevice();
      if (!g_dev) { set_err(@"no Metal device"); return; }
      g_queue = [g_dev newCommandQueue];
      g_vpt = env_int("MF_METAL_VPT", g_vpt);
      g_radx = env_int("MF_METAL_RADX", g_radx);
      /* Each thread does VPT/radix butterflies per stage, so a radix above
         VPT would silently do none. */
      if (!is_pow2((size_t)g_vpt) || !is_pow2((size_t)g_radx) || g_radx < 2 ||
          g_radx > 16 || g_radx > g_vpt || g_vpt > 32) {
        set_err(@"MF_METAL_VPT/MF_METAL_RADX: need powers of two, 2 <= RADX <= 16, RADX <= VPT <= 32");
        return;
      }
      g_libs = [NSMutableDictionary dictionary];
      /* MF_METAL_SOURCE points at a kernels.metal to use instead of the
         embedded copy, so the kernels can be edited without rebuilding. */
      const char *path = getenv("MF_METAL_SOURCE");
      if (path && *path) {
        NSError *e = nil;
        g_src = [NSString stringWithContentsOfFile:@(path) encoding:NSUTF8StringEncoding error:&e];
        if (!g_src) { set_err([e localizedDescription]); return; }
      } else {
        g_src = @(MFM_SRC);
      }
      ok = g_queue != nil;
    }
  });
  return ok;
}

int mfm_available(void) { return init_device(); }

const char *mfm_device_name(void) {
  if (!init_device()) return NULL;
  static char name[128];
  snprintf(name, sizeof name, "%s", [[g_dev name] UTF8String]);
  return name;
}

int mfm_supported(size_t n) { return is_pow2(n) && n >= 256 && n <= ((size_t)1 << 21); }

/* ------------------------------------------------------------ pipelines */

/* A library for one tile shape: L-point transforms, M per threadgroup. */
static id<MTLLibrary> library(int L, int M, int ifast) {
  int lg = ilog2((size_t)L), lr = ilog2(RADX);
  int nst = L <= RADX ? 1 : (lg + lr - 1) / lr;
  int rad0 = 1 << (lg - (nst - 1) * lr);
  NSString *key = [NSString stringWithFormat:@"%d,%d,%d", L, M, ifast];
  @synchronized(g_libs) {
    id<MTLLibrary> lib = g_libs[key];
    if (lib) return lib;
    MTLCompileOptions *o = [MTLCompileOptions new];
    o.preprocessorMacros = @{
      @"FFT_L" : @(L), @"FFT_M" : @(M), @"IFAST" : @(ifast), @"VPT" : @(VPT),
      @"RADX" : @(RADX), @"NST" : @(nst), @"RAD0" : @(rad0)};
    /* Safe math: the peak search compares magnitudes that the CPU computes
       IEEE-exactly, and the tests hold the two to a few ulps. */
    if (@available(macOS 15.0, *)) {
      o.mathMode = MTLMathModeSafe;
    } else {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
      o.fastMathEnabled = NO;
#pragma clang diagnostic pop
    }
    NSError *e = nil;
    lib = [g_dev newLibraryWithSource:g_src options:o error:&e];
    if (!lib) { set_err([e localizedDescription]); return nil; }
    g_libs[key] = lib;
    return lib;
  }
}

static id<MTLComputePipelineState> pipeline(id<MTLLibrary> lib, NSString *fn, NSUInteger need) {
  if (!lib) return nil;
  id<MTLFunction> f = [lib newFunctionWithName:fn];
  if (!f) { set_err([@"missing kernel " stringByAppendingString:fn]); return nil; }
  NSError *e = nil;
  id<MTLComputePipelineState> ps = [g_dev newComputePipelineStateWithFunction:f error:&e];
  if (!ps) { set_err([e localizedDescription]); return nil; }
  if (need && [ps maxTotalThreadsPerThreadgroup] < need) {
    set_err([NSString stringWithFormat:@"%@ allows %lu threads per threadgroup, needs %lu",
             fn, (unsigned long)[ps maxTotalThreadsPerThreadgroup], (unsigned long)need]);
    return nil;
  }
  return ps;
}

/* ------------------------------------------------------------ plan */

struct mfm_plan {
  size_t n;
  int nd, nt;
  int fourstep;
  int M;                    /* one-pass: pairs per threadgroup            */
  int A, B, W2, M1, H;      /* four-step shape; M1 rows per pass-1 group  */
  int chunk;                /* four-step: pairs per scratch fill          */
  id<MTLBuffer> D, T;       /* spectra, [nd][n] and [nt][n]               */
  id<MTLBuffer> tw, twA, twlo, twhi;
  id<MTLBuffer> scratch, part;
  id<MTLBuffer> oidx, oval, omag;
  size_t ocap;              /* rows*bins the output buffers hold          */
  id<MTLBuffer> gpart;      /* one-pass: wide-bin chunk maxima, per group */
  size_t gcap;
  id<MTLComputePipelineState> small, pass1, pass2, fin_t, fin_g;
};

/* exp(+2 pi i q / L) for q in [0, count), scaled so that step = L/count... */
static id<MTLBuffer> twiddles(size_t count, size_t period, size_t stride) {
  id<MTLBuffer> b = [g_dev newBufferWithLength:count * 8 options:MTLResourceStorageModeShared];
  float *w = (float *)[b contents];
  for (size_t q = 0; q < count; q++) {
    double a = 2.0 * M_PI * (double)(q * stride % period) / (double)period;
    w[2 * q] = (float)cos(a);
    w[2 * q + 1] = (float)sin(a);
  }
  return b;
}

mfm_plan *mfm_create(size_t n, int ndata, int ntmpl) {
  g_err[0] = 0;
  if (!init_device()) return NULL;
  if (!mfm_supported(n) || ndata < 1 || ntmpl < 1) {
    set_err(@"unsupported shape"); return NULL;
  }
  @autoreleasepool {
    mfm_plan *p = (mfm_plan *)calloc(1, sizeof *p);
    if (!p) return NULL;
    p->n = n; p->nd = ndata; p->nt = ntmpl;
    int tile = env_int("MF_METAL_TILE", TILE);
    p->fourstep = n > (size_t)tile;
    MTLResourceOptions sh = MTLResourceStorageModeShared;
    MTLResourceOptions pv = MTLResourceStorageModePrivate;
    p->D = [g_dev newBufferWithLength:(size_t)ndata * n * 8 options:sh];
    p->T = [g_dev newBufferWithLength:(size_t)ntmpl * n * 8 options:sh];
    if (!p->D || !p->T) { set_err(@"out of GPU memory for spectra"); mfm_destroy(p); return NULL; }
    if (!p->fourstep) {
      p->M = (int)((size_t)tile / n); if (p->M < 1) p->M = 1;
      p->tw = twiddles(n, n, 1);
      p->small = pipeline(library((int)n, p->M, 1), @"mf_small", (NSUInteger)(p->M * n / VPT));
      if (!p->small) { mfm_destroy(p); return NULL; }
    } else {
      /* n = A*B.  Pass 1 reads rows of B contiguously; pass 2 transforms
         W2 columns of A at once.  Defaults are measured on an M2 (swept over
         A = 2^4..2^10 and W2 = 4..64): A = 32 up to 2^17, then the smallest
         A that keeps B within one tile; W2 = 32 up to 2^16, then 16.  The
         spread across the sweep was under 10% near the optimum -- past 2^17
         both passes are bound by DRAM, not by the tile shape. */
      int lg = ilog2(n);
      int la = env_int("MF_METAL_LOGA", lg <= 17 ? 5 : lg - 12);
      if (la < 1) la = 1;
      if (la > lg - 4) la = lg - 4;
      p->A = 1 << la; p->B = (int)(n >> la);
      if (p->B > tile) { p->B = tile; p->A = (int)(n / (size_t)tile); }
      int w2 = env_int("MF_METAL_W2", lg <= 16 ? 32 : 16);
      if (w2 > tile / p->A) w2 = tile / p->A;
      if (w2 > p->B) w2 = p->B;
      if (w2 < 1) w2 = 1;
      p->W2 = w2;
      p->M1 = tile / p->B; if (p->M1 > p->A) p->M1 = p->A; if (p->M1 < 1) p->M1 = 1;
      if ((size_t)p->M1 * p->B < VPT || (size_t)p->A * p->W2 < VPT) {
        set_err(@"four-step tile too small"); mfm_destroy(p); return NULL;
      }
      p->H = 1 << ((lg + 1) / 2);
      p->tw = twiddles((size_t)p->B, (size_t)p->B, 1);
      p->twA = twiddles((size_t)p->A, (size_t)p->A, 1);
      p->twlo = twiddles((size_t)p->H, n, 1);
      p->twhi = twiddles(n / (size_t)p->H, n, (size_t)p->H);
      id<MTLLibrary> l1 = library(p->B, p->M1, 1), l2 = library(p->A, p->W2, 0);
      p->pass1 = pipeline(l1, @"mf_pass1", (NSUInteger)(p->M1 * p->B / VPT));
      p->pass2 = pipeline(l2, @"mf_pass2", (NSUInteger)(p->A * p->W2 / VPT));
      p->fin_t = pipeline(l2, @"mf_final_thread", 0);
      p->fin_g = pipeline(l2, @"mf_final_tg", 256);
      if (!p->pass1 || !p->pass2 || !p->fin_t || !p->fin_g) { mfm_destroy(p); return NULL; }
      /* Scratch holds one intermediate per pair in flight.  Bounded, so a
         large batch runs as several fills of one command buffer. */
      size_t budget = (size_t)env_int("MF_METAL_SCRATCH_MB", 64) << 20;
      size_t pairs = (size_t)ndata * ntmpl;
      size_t c = budget / (n * 8); if (c < 1) c = 1; if (c > pairs) c = pairs;
      p->chunk = (int)c;
      p->scratch = [g_dev newBufferWithLength:c * n * 8 options:pv];
      p->part = [g_dev newBufferWithLength:c * (n / (size_t)p->W2) * 2 * 16 options:pv];
      if (!p->scratch || !p->part) { set_err(@"out of GPU memory for scratch"); mfm_destroy(p); return NULL; }
    }
    return p;
  }
}

void mfm_destroy(mfm_plan *p) {
  if (!p) return;
  @autoreleasepool {
    p->D = p->T = p->tw = p->twA = p->twlo = p->twhi = nil;
    p->scratch = p->part = p->oidx = p->oval = p->omag = p->gpart = nil;
    p->small = p->pass1 = p->pass2 = p->fin_t = p->fin_g = nil;
  }
  free(p);
}

void mfm_config(const mfm_plan *p, int *fourstep, int *a, int *b, int *w) {
  if (!p) return;
  if (fourstep) *fourstep = p->fourstep;
  if (a) *a = p->fourstep ? p->A : p->M;
  if (b) *b = p->fourstep ? p->B : (int)p->n;
  if (w) *w = p->fourstep ? p->W2 : 0;
}

size_t mfm_nbins(const mfm_plan *p, size_t binsize, size_t start, size_t end) {
  if (!p || !binsize) return 0;
  if (end > p->n) end = p->n;
  if (start >= end) return 0;
  return (end - start + binsize - 1) / binsize;
}

/* Spectra are stored as given for the one-pass kernel, and as rows of the
   four-step split -- x[f1 + A*f2] at f1*B + f2 -- for the other, so pass 1
   reads each row contiguously.  Paid once per segment. */
static int store(mfm_plan *p, id<MTLBuffer> buf, int i, int count, const float *spec) {
  if (!p || i < 0 || i >= count) return -1;
  float *dst = (float *)[buf contents] + (size_t)2 * i * p->n;
  if (!p->fourstep) { memcpy(dst, spec, p->n * 8); return 0; }
  const size_t A = (size_t)p->A, B = (size_t)p->B;
  for (size_t f2 = 0; f2 < B; f2++)
    for (size_t f1 = 0; f1 < A; f1++) {
      const size_t s = f1 + A * f2, d = f1 * B + f2;
      dst[2 * d] = spec[2 * s];
      dst[2 * d + 1] = spec[2 * s + 1];
    }
  return 0;
}

int mfm_set_data(mfm_plan *p, int d, const float *spec) { return store(p, p ? p->D : nil, d, p ? p->nd : 0, spec); }
int mfm_set_template(mfm_plan *p, int t, const float *spec) { return store(p, p ? p->T : nil, t, p ? p->nt : 0, spec); }

int mfm_run(mfm_plan *p, int d0, int nd, int t0, int nt,
            size_t binsize, float threshold, size_t start, size_t end,
            long long *index, float *value, float *magnitude, int *counts) {
  if (!p || nd < 1 || nt < 1 || !binsize) return 0;
  if (d0 < 0 || d0 + nd > p->nd || t0 < 0 || t0 + nt > p->nt) return -1;
  if (end > p->n) end = p->n;
  if (start >= end) return 0;
  if (binsize > end - start) binsize = end - start;   /* same bins, and no overflow below */
  const size_t nb = (end - start + binsize - 1) / binsize;
  const size_t npairs = (size_t)nd * nt;
  const size_t rows = npairs * nb;
  @autoreleasepool {
    if (rows > p->ocap) {
      MTLResourceOptions sh = MTLResourceStorageModeShared;
      p->oidx = [g_dev newBufferWithLength:rows * 4 options:sh];
      p->oval = [g_dev newBufferWithLength:rows * 8 options:sh];
      p->omag = [g_dev newBufferWithLength:rows * 4 options:sh];
      if (!p->oidx || !p->oval || !p->omag) { p->ocap = 0; set_err(@"out of GPU memory for peaks"); return -1; }
      p->ocap = rows;
    }
    mfm_params P = {0};
    P.n = (uint32_t)p->n; P.ntl = (uint32_t)nt; P.d0 = (uint32_t)d0; P.t0 = (uint32_t)t0;
    P.ndl = (uint32_t)nd;
    /* Keep the smaller side cached and stream the larger through once. */
    P.dinner = (uint32_t)env_int("MF_METAL_DINNER", nd <= nt);
    P.npairs = (uint32_t)npairs; P.nb = (uint32_t)nb; P.bs = (uint32_t)binsize;
    P.ws = (uint32_t)start; P.we = (uint32_t)end;
    P.t2 = threshold > 0.f ? threshold * threshold : -1.f;
    P.A = (uint32_t)p->A; P.B = (uint32_t)p->B; P.W2 = (uint32_t)p->W2; P.H = (uint32_t)p->H;

    id<MTLCommandBuffer> cb = [g_queue commandBufferWithUnretainedReferences];
    id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
    if (!p->fourstep) {
      [enc setComputePipelineState:p->small];
      [enc setBuffer:p->D offset:0 atIndex:0];
      [enc setBuffer:p->T offset:0 atIndex:1];
      [enc setBuffer:p->tw offset:0 atIndex:2];
      [enc setBuffer:p->oidx offset:0 atIndex:3];
      [enc setBuffer:p->oval offset:0 atIndex:4];
      [enc setBuffer:p->omag offset:0 atIndex:5];
      [enc setBytes:&P length:sizeof P atIndex:6];
      NSUInteger groups = (npairs + (size_t)p->M - 1) / (size_t)p->M;
      /* PARTMAX in kernels.metal */
      const size_t partmax = 3 * (size_t)p->M * p->n / 128 + (size_t)p->M + 4;
      if (groups * partmax > p->gcap) {
        p->gpart = [g_dev newBufferWithLength:groups * partmax * 8 options:MTLResourceStorageModePrivate];
        if (!p->gpart) { p->gcap = 0; [enc endEncoding]; set_err(@"out of GPU memory"); return -1; }
        p->gcap = groups * partmax;
      }
      [enc setBuffer:p->gpart offset:0 atIndex:7];
      [enc dispatchThreadgroups:MTLSizeMake(groups, 1, 1)
          threadsPerThreadgroup:MTLSizeMake((NSUInteger)p->M * p->n / VPT, 1, 1)];
    } else {
      const size_t runsPerBin = (binsize + (size_t)p->W2 - 1) / (size_t)p->W2 + 1;
      const int wide = runsPerBin > 64;
      /* Diagnostic: stop after pass 1 or 2, to time the passes apart. */
      const int passes = env_int("MF_METAL_PASSES", 3);
      for (size_t c0 = 0; c0 < npairs; c0 += (size_t)p->chunk) {
        const size_t nc = npairs - c0 < (size_t)p->chunk ? npairs - c0 : (size_t)p->chunk;
        P.pair0 = (uint32_t)c0; P.nchunk = (uint32_t)nc;

        [enc setComputePipelineState:p->pass1];
        [enc setBuffer:p->D offset:0 atIndex:0];
        [enc setBuffer:p->T offset:0 atIndex:1];
        [enc setBuffer:p->tw offset:0 atIndex:2];
        [enc setBuffer:p->scratch offset:0 atIndex:3];
        [enc setBuffer:p->twlo offset:0 atIndex:4];
        [enc setBuffer:p->twhi offset:0 atIndex:5];
        [enc setBytes:&P length:sizeof P atIndex:6];
        [enc dispatchThreadgroups:MTLSizeMake(nc * (size_t)(p->A / p->M1), 1, 1)
            threadsPerThreadgroup:MTLSizeMake((NSUInteger)p->M1 * p->B / VPT, 1, 1)];

        if (passes < 2) continue;
        [enc setComputePipelineState:p->pass2];
        [enc setBuffer:p->scratch offset:0 atIndex:0];
        [enc setBuffer:p->twA offset:0 atIndex:1];
        [enc setBuffer:p->part offset:0 atIndex:2];
        [enc setBuffer:p->oidx offset:0 atIndex:3];
        [enc setBuffer:p->oval offset:0 atIndex:4];
        [enc setBuffer:p->omag offset:0 atIndex:5];
        [enc setBytes:&P length:sizeof P atIndex:6];
        [enc dispatchThreadgroups:MTLSizeMake(nc * (size_t)(p->B / p->W2), 1, 1)
            threadsPerThreadgroup:MTLSizeMake((NSUInteger)p->A * p->W2 / VPT, 1, 1)];

        if (passes < 3) continue;
        [enc setComputePipelineState:wide ? p->fin_g : p->fin_t];
        [enc setBuffer:p->part offset:0 atIndex:0];
        [enc setBuffer:p->oidx offset:0 atIndex:1];
        [enc setBuffer:p->oval offset:0 atIndex:2];
        [enc setBuffer:p->omag offset:0 atIndex:3];
        [enc setBytes:&P length:sizeof P atIndex:4];
        if (wide)
          [enc dispatchThreadgroups:MTLSizeMake(nc * nb, 1, 1)
              threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
        else
          [enc dispatchThreads:MTLSizeMake(nc * nb, 1, 1)
              threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
      }
    }
    [enc endEncoding];
    [cb commit];
    [cb waitUntilCompleted];
    g_gpu_seconds = [cb GPUEndTime] - [cb GPUStartTime];
    if ([cb status] != MTLCommandBufferStatusCompleted) {
      set_err([[cb error] localizedDescription] ?: @"command buffer failed");
      return -1;
    }
    const int *ix = (const int *)[p->oidx contents];
    const float *vl = (const float *)[p->oval contents];
    const float *mg = (const float *)[p->omag contents];
    memcpy(value, vl, rows * 8);
    memcpy(magnitude, mg, rows * 4);
    int total = 0;
    for (size_t r = 0; r < npairs; r++) {
      int c = 0;
      for (size_t j = 0; j < nb; j++) {
        const int k = ix[r * nb + j];
        index[r * nb + j] = k;
        c += k >= 0;
      }
      if (counts) counts[r] = c;
      total += c;
    }
    return total;
  }
}
