import math, sys
# Generate fully-unrolled Stockham autosort SoA vector FFT codelets.
# Data: __m512 xr[n], xi[n]  (element index = transform index; SIMD lanes = independent transforms)
def wconst(k,n):
    a=-2*math.pi*k/n
    return (math.cos(a), math.sin(a))
def trivial(c,s,tol=1e-12):
    for (v,name) in ((1,0),):
        pass
    if abs(c-1)<tol and abs(s)<tol: return "1"
    if abs(c+1)<tol and abs(s)<tol: return "-1"
    if abs(c)<tol and abs(s+1)<tol: return "-i"
    if abs(c)<tol and abs(s-1)<tol: return "+i"
    return None

class Gen:
    def __init__(s,n,name):
        s.n=n; s.name=name; s.L=[]; s.consts={}; s.nc=0
    def emit(s,l): s.L.append("  "+l)
    def const(s,c,v):
        key=("%.17g"%v)
        if key not in s.consts:
            nm="c%d"%len(s.consts); s.consts[key]=nm
        return s.consts[key]
    # complex multiply (re,im) by constant twiddle (c,sn) -> new names
    def cmul(s,ar,ai,c,sn,out):
        t=trivial(c,sn)
        orr,oii=out
        if t=="1":
            s.emit("__m512 %s=%s, %s=%s;"%(orr,ar,oii,ai)); return
        if t=="-1":
            s.emit("__m512 %s=_mm512_sub_ps(Z,%s), %s=_mm512_sub_ps(Z,%s);"%(orr,ar,oii,ai)); return
        if t=="-i":   # (a)(-i) = ai_ - i*ar
            s.emit("__m512 %s=%s, %s=_mm512_sub_ps(Z,%s);"%(orr,ai,oii,ar)); return
        if t=="+i":
            s.emit("__m512 %s=_mm512_sub_ps(Z,%s), %s=%s;"%(orr,ai,oii,ar)); return
        cc=s.const("c",c); ss=s.const("s",sn)
        s.emit("__m512 %s=_mm512_fmsub_ps(%s,%s,_mm512_mul_ps(%s,%s));"%(orr,ar,cc,ai,ss))
        s.emit("__m512 %s=_mm512_fmadd_ps(%s,%s,_mm512_mul_ps(%s,%s));"%(oii,ar,ss,ai,cc))
    def run(s,radices):
        n=s.n; N=n; sstride=1; cur=n
        A=("ar","ai"); B=("br","bi")
        X,Y=A,B; flips=0
        for r in radices:
            m=cur//r
            for j in range(m):
                for q in range(sstride):
                    # load
                    ins=[]
                    for k in range(r):
                        idx=q+sstride*(j+m*k)
                        ins.append(("%s[S*%d]"%(X[0],idx),"%s[S*%d]"%(X[1],idx)))
                    outs=s.dft(r,ins)
                    for l in range(r):
                        c,sn=wconst(j*sstride*l, N)
                        o=("t%d_r"%s.nc,"t%d_i"%s.nc); s.nc+=1
                        s.cmul(outs[l][0],outs[l][1],c,sn,o)
                        idx=q+sstride*(r*j+l)
                        s.emit("%s[S*%d]=%s; %s[S*%d]=%s;"%(Y[0],idx,o[0],Y[1],idx,o[1]))
            X,Y=Y,X; flips^=1; cur=m; sstride*=r
        return flips
    def dft(s,r,ins):
        """emit an r-point DFT, return list of (re,im) names"""
        def nm():
            v=("u%d_r"%s.nc,"u%d_i"%s.nc); s.nc+=1; return v
        def add(a,b):
            o=nm(); s.emit("__m512 %s=_mm512_add_ps(%s,%s), %s=_mm512_add_ps(%s,%s);"%(o[0],a[0],b[0],o[1],a[1],b[1])); return o
        def sub(a,b):
            o=nm(); s.emit("__m512 %s=_mm512_sub_ps(%s,%s), %s=_mm512_sub_ps(%s,%s);"%(o[0],a[0],b[0],o[1],a[1],b[1])); return o
        def muli(a):   # multiply by -i  (DIF forward convention)
            o=nm(); s.emit("__m512 %s=%s, %s=_mm512_sub_ps(Z,%s);"%(o[0],a[1],o[1],a[0])); return o
        if r==2:
            return [add(ins[0],ins[1]), sub(ins[0],ins[1])]
        if r==4:
            t0=add(ins[0],ins[2]); t1=sub(ins[0],ins[2])
            t2=add(ins[1],ins[3]); t3=muli(sub(ins[1],ins[3]))
            return [add(t0,t2), add(t1,t3), sub(t0,t2), sub(t1,t3)]
        if r==8:
            # radix-8 = two radix-4 on even/odd then combine with w8^k
            e=[ins[0],ins[2],ins[4],ins[6]]; o=[ins[1],ins[3],ins[5],ins[7]]
            E=s.dft(4,e); O=s.dft(4,o)
            res=[None]*8
            for k in range(4):
                c,sn=wconst(k,8)
                tw=("v%d_r"%s.nc,"v%d_i"%s.nc); s.nc+=1
                s.cmul(O[k][0],O[k][1],c,sn,tw)
                res[k]=add(E[k],tw); res[k+4]=sub(E[k],tw)
            return res
        raise Exception("radix %d"%r)

def build(n,radices,name):
    g=Gen(n,name); flip=g.run(radices)
    body="\n".join(g.L)
    cdefs="\n".join("  const __m512 %s=_mm512_set1_ps(%sf);"%(v,k) for k,v in g.consts.items())
    sig=("static inline int %s(__m512*ar,__m512*ai,__m512*br,__m512*bi,const long S){\n"
         "  const __m512 Z=_mm512_setzero_ps();\n%s\n%s\n  return %d;\n}\n")%(name,cdefs,body,flip)
    return sig

if __name__=="__main__":
    out=["/* generated by gen.py - do not edit */","#include <immintrin.h>",""]
    out.append(build(32,[8,4],"fft32_84"))
    out.append(build(32,[4,4,2],"fft32_442"))
    out.append(build(16,[4,4],"fft16_44"))
    out.append(build(64,[8,8],"fft64_88"))
    open("codelets.h","w").write("\n".join(out))
    print("generated codelets.h")
